[package]
name = "revault_tx"
version = "0.0.1"
authors = ["Antoine Poinsot <darosior@protonmail.com>"]
edition = "2018"

[features]
use-serde = ["serde", "base64"]

[dependencies]
bitcoin = "0.24"
bitcoinconsensus = "0.19.0-1"
miniscript = { version = "2.0.0", features = ["compiler"] }

serde = { version = "1.0", optional = true }
base64 = { version = "0.13.0", optional = true }

[dev-dependencies]
bitcoin = { version = "0.24", features = ["rand"] }
serde_json = "1.0.58"
